"""Constantes de estados, pinos e tempos do sistema de irrigacao."""

MONITORANDO = "MONITORANDO"
SOLO_SECO = "SOLO_SECO"
IRRIGANDO = "IRRIGANDO"
AGUARDANDO = "AGUARDANDO"

STATE_LABELS = {
    MONITORANDO: "Monitorando",
    SOLO_SECO: "Solo seco",
    IRRIGANDO: "Irrigando",
    AGUARDANDO: "Aguardando",
}

SOIL_PIN = 34
SERVO_PIN = 18
LED_GREEN_PIN = 25
LED_BLUE_PIN = 26
LED_RED_PIN = 27
OLED_SDA_PIN = 21
OLED_SCL_PIN = 22

ADC_MAX = 4095
SERVO_FREQ = 50
SERVO_CLOSED_ANGLE = 0
SERVO_OPEN_ANGLE = 90

READ_INTERVAL_MS = 500
DISPLAY_INTERVAL_MS = 250
DRY_CONFIRMATION_MS = 1500
IRRIGATION_DURATION_MS = 5000
POST_IRRIGATION_WAIT_MS = 4000

DRY_THRESHOLD = 35
RECOVERY_THRESHOLD = 45
